In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("skin clinic campaign.csv")

df.head()

,CustID,Gender,AgeGroup,Purchase_Last_Quarter,Unique_Products_Purchased,Response_to_Campaign
0,100001,Female,30-50,Yes,9,Yes
1,100002,Male,>50,Yes,15,No
2,100003,Male,>50,Yes,11,No
3,100004,Female,30-50,No,6,No
4,100005,Female,<30,Yes,13,Yes

In [5]:
df.shape

(10000, 6)

In [6]:
df["Response"] = df["Response_to_Campaign"].map({"Yes":1, "No":0})

df.head()

,CustID,Gender,AgeGroup,Purchase_Last_Quarter,Unique_Products_Purchased,Response_to_Campaign,Response
0,100001,Female,30-50,Yes,9,Yes,1
1,100002,Male,>50,Yes,15,No,0
2,100003,Male,>50,Yes,11,No,0
3,100004,Female,30-50,No,6,No,0
4,100005,Female,<30,Yes,13,Yes,1

In [7]:
gender_response = (
    df.groupby("Gender")["Response"]
    .mean()
    .mul(100)
    .round(2)
    .reset_index(name="Response Rate")
)

gender_response

   Gender  Response Rate
0  Female          43.77
1    Male          34.08

In [8]:
df["AgeGroup"].value_counts()

AgeGroup
30-50    4992
>50      2509
<30      2499
Name: count, dtype: int64

In [9]:
age_response = (
    df.groupby("AgeGroup")["Response"]
      .mean()
      .mul(100)
      .round(2)
      .reset_index(name="Response Rate")
)

age_response

  AgeGroup  Response Rate
0    30-50          47.06
1      <30          32.93
2      >50          32.60

In [10]:
age_order = ["<30", "30-50", ">50"]

df["AgeGroup"] = pd.Categorical(
    df["AgeGroup"],
    categories=age_order,
    ordered=True
)

In [11]:
age_response = (
    df.groupby("AgeGroup", observed=True)["Response"]
      .mean()
      .mul(100)
      .round(2)
      .reset_index(name="Response Rate (%)")
)

age_response

  AgeGroup  Response Rate (%)
0      <30              32.93
1    30-50              47.06
2      >50              32.60

In [12]:
df["Purchase_Last_Quarter"].value_counts()

Purchase_Last_Quarter
Yes    6514
No     3486
Name: count, dtype: int64

In [13]:
purchase_response = (
    df.groupby("Purchase_Last_Quarter")["Response"]
      .mean()
      .mul(100)
      .round(2)
      .reset_index(name="Response Rate")
)

purchase_response

  Purchase_Last_Quarter  Response Rate
0                    No          21.69
1                   Yes          49.65

In [14]:
df["Product_Usage"] = pd.cut(
    df["Unique_Products_Purchased"],
    bins=[0, 4, 8, float('inf')],
    labels=["1-4", "5-8", ">8"]
)

df[["Unique_Products_Purchased", "Product_Usage"]].head(10)

   Unique_Products_Purchased Product_Usage
0                          9            >8
1                         15            >8
2                         11            >8
3                          6           5-8
4                         13            >8
5                          5           5-8
6                         12            >8
7                          7           5-8
8                         15            >8
9                          7           5-8

In [15]:
df["Product_Usage"].value_counts().sort_index()

Product_Usage
1-4    2091
5-8    3703
>8     4206
Name: count, dtype: int64

In [16]:
product_response = (
    df.groupby("Product_Usage", observed=True)["Response"]
      .mean()
      .mul(100)
      .round(2)
      .reset_index(name="Response Rate")
)

product_response

  Product_Usage  Response Rate
0           1-4          18.08
1           5-8          38.48
2            >8          52.00